---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_path: test/shared
  attributes:
    apache:
      default_site_enabled: false

platforms:
  - name: debian-7.4
    attributes:
      apt:
        compile_time_update: true
    run_list:
      - recipe[apt::default]
  - name: ubuntu-12.04
    driver_config:
      network:
      - ["forwarded_port", {guest: 8080, host: 8080}]
    attributes:
      apt:
        compile_time_update: true
    run_list:
      - recipe[apt::default]
#  - name: ubuntu-13.10
#    # AH00526: Syntax error on line 11 of /etc/apache2/apache2.conf:
#    # Invalid command 'LockFile', perhaps misspelled or defined by a module not included in the server configuration
#    # Action 'configtest' failed.
#    run_list:
#    - recipe[apt::default]
#  - name: centos-6.4
#  - name: centos-6.5


suites:
  - name: DB-H2
    run_list:
      - recipe[gerrit::default]
    excludes: ["ubuntu-13.10"]
  - name: DB-MYSQL
    run_list:
      - recipe[gerrit::default]
    excludes: ["ubuntu-12.04", "centos-6.4", "centos-6.5"]
    attributes:
      gerrit:
        database:
          type: MYSQL
      mysql:
        server_debian_password: "foo"
        server_root_password: "foo"
        server_repl_password: "foo"
  - name: DB-POSTGRESQL
    run_list:
      - recipe[gerrit::default]
    excludes:
      - centos-6.4 # fails with: "Undefined method or attribute `action' on `node'" in build-essentials
      - centos-6.5 # fails with: "Undefined method or attribute `action' on `node'" in build-essentials
      - ubuntu-12.04 # works only at the 2nd "kitchen converge" try.. some apt-get update issue
    attributes:
      gerrit:
        database:
          type: POSTGRESQL
      postgresql:
        password:
          postgres: "foo"
  - name: PROXY-NONE
    run_list:
      - recipe[gerrit::default]
    attributes:
      gerrit:
        proxy:
          enable: false
          ssl: false
